#!/usr/bin/env bash
grep=""
dry_run="0"
action=""

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    case "$1" in
        --dry)
            dry_run="1"
	    shift
	    ;;
	--action=*)
	    action="${1#*=}"
	    shift
	    ;;
	*)
	    grep="$1"
	    shift
	    ;;
    esac
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"

update_files() {
    log "copying over files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}

            if basename $directory | grep -vq "$grep"; then
                log "grep \"$grep\" filtered out $directory"
                continue
            fi

            log "    removing: rm -rf $directory"

            if [[ $dry_run == "0" ]]; then
                rm -rf $directory
            fi

            log "    copying env: cp $c $2"
            if [[ $dry_run == "0" ]]; then
                cp -r ./$c $2
            fi
        done

    )
    popd &> /dev/null
}

copy() {
    log "removing: $2"
    if [[ $dry_run == "0" ]]; then
        rm $2
    fi
    log "copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp $1 $2
    fi
}

if [[ $action == ".config" ]]; then
    update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME
fi

if [[ $action == ".local" ]]; then
    update_files $DEV_ENV/env/.local $HOME/.local
fi

if [[ $action == "copy" ]]; then
    copy $DEV_ENV/tmux-sessionizer/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
    copy $DEV_ENV/env/.bash_profile $HOME/.bash_profile
    copy $DEV_ENV/env/.bashrc $HOME/.bashrc
    # copy $DEV_ENV/env/.xprofile $HOME/.xprofile
    copy $DEV_ENV/env/.tmux-sessionizer $HOME/.tmux-sessionizer
    copy $DEV_ENV/dev-env $HOME/.local/scripts/dev-env

    # build daydream's client and server
    # pushd $DEV_ENV/daydream &> /dev/null
    # ./build
    # popd &> /dev/null

    mkdir -p $HOME/.local/bin
    # copy $DEV_ENV/daydream/opencode-client $HOME/.local/bin/opencode-client
    # copy $DEV_ENV/daydream/opencode-server $HOME/.local/bin/opencode-server
fi

hyprctl reload
