#!/usr/bin/env bash

paru -S --needed --noconfirm \
    elephant-bin elephant-bluetooth-bin elephant-calc-bin elephant-clipboard-bin elephant-desktopapplications-bin \
    elephant-files-bin elephant-menus-bin elephant-providerlist-bin elephant-runner-bin elephant-symbols-bin \
    elephant-todo-bin elephant-unicode-bin elephant-websearch-bin

elephant service enable
systemctl --user start elephant.service
