#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm \
    bluetui bluez brightnessctl chromium gtk4-layer-shell hyprland hyprpicker hyprpolkitagent hyprsunset libnewt libnotify mako \
    nautilus noto-fonts pipewire pipewire-alsa pipewire-jack pipewire-pulse plymouth qt5-wayland qt6-wayland sddm swaybg swayosd ttf-jetbrains-mono-nerd uwsm \
    ttf-nerd-fonts-symbols-common waybar wireplumber wl-clipboard xdg-desktop-portal-gtk xdg-desktop-portal-hyprland

paru -S --needed --noconfirm \
    hyprshade limine-mkinitcpio-hook walker xdg-terminal-exec

# For limine-mkinitcpio-hook
# sudo limine-update

# For plymouth
# sudo limine-mkinitcpio

sudo systemctl enable --now bluetooth.service
sudo systemctl enable sddm.service
systemctl enable --now --user ssh-agent.service
