#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm \
    alacritty btop eza fastfetch ffmpeg fzf jp2a ripgrep rsync starship unzip wiremix wget zoxide

paru -S --needed --noconfirm \
    ltunify python-terminaltexteffects try
